version: "3"
services: 
  zulu:
    build: 
      context: ./zulu
      dockerfile: Dockerfile
    ports: 
    - "8080:8080"
  oracle:
    build: 
      context: ./oracle
      dockerfile: Dockerfile
    ports: 
    - "8081:8080"
  openjdk:
    build: 
      context: ./openjdk
      dockerfile: Dockerfile
    ports: 
    - "8082:8080"
  grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
  prometheus:
    image: prom/prometheus
    volumes:
    - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
    - "9090:9090"